"""Generate small SYNTHETIC Swift fixtures through production conversion/evidence/API code."""
import copy
import json
import os
from pathlib import Path
import sys
import tempfile
sys.path.insert(0,str(Path(__file__).resolve().parent))
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from fixtures import records, collection, event, MemoryRegistry,handle
from registry.contract import convert
from registry.evidence import attach
from registry.cli import prepare
from test_bridge import synthetic_scene,patch


def generate(out):
    os.environ['COGNITO_CLIENT_ID']='synthetic-client'
    out.mkdir(parents=True,exist_ok=True)
    c=collection();second=copy.deepcopy(c['features'][0]);second['properties']['type']='Hoffmann'
    second['properties']['scene_id']='SYNTHETIC-B';c['features'].append(second)
    c['kilnwatch']['scenes'].append({'id':'SYNTHETIC-B','acquired_at':'2026-10-05T05:41:03.148Z'})
    with tempfile.TemporaryDirectory() as d:
        directory=Path(d)
        detection=directory/'synthetic.geojson';detection.write_text(json.dumps(c))
        source,source_sha,_,_=prepare(detection,'Hapur',imported_at='2026-10-09T15:00:00Z')
        p=source[0]['payload'];scene=synthetic_scene(directory,p['provenance']['scene_id'],p['last_seen'])
        meta,_=patch(scene,p,directory/'images')
        meta.pop('source_assets')  # Test-only local raster paths are not portable fixture provenance.
        manifest={'schema_version':1,'input_sha256':source_sha,'entries':[{'observation_id':source[0]['observation_id'],'model_sha256':'a'*64,'before':None,'after':meta}]}
        path=directory/'images'/'manifest.json';path.write_text(json.dumps(manifest));attach(source,path,source_sha)
    repo=MemoryRegistry(source)
    cases={'list':event(),'detail':event('/kilns/'+source[0]['payload']['kiln_id']),
           'page1':event(query={'district':'Hapur','limit':'1'})}
    cursor=source[0]['payload']['kiln_id'] if source[0]['payload']['kiln_id']<source[1]['payload']['kiln_id'] else source[1]['payload']['kiln_id']
    cases['page2']=event(query={'district':'Hapur','limit':'1','cursor':cursor})
    for name,e in cases.items():
        response=handle(e,repo.factory)
        assert response['statusCode']==200
        (out/(name+'.json')).write_text(json.dumps(json.loads(response['body']),indent=2)+'\n')
    (out/'README.md').write_text('SYNTHETIC TEST FIXTURES. Generated by AWS/tests/generate_contract.py through production conversion, evidence validation, and API response serialization. Not real detections, imagery, database persistence or AWS proof. Regenerate and verify deterministic JSON before swift test.\n')


if __name__=='__main__':
    generate(Path(__file__).resolve().parents[2]/'App/Packages/KilnWatchCore/Tests/KilnWatchCoreTests/BridgeFixtures')
