import { Link } from 'react-router-dom';
import { useLocale } from '../i18n';
import { config } from '../data/client';

export function InfoPage({ kind }: { kind: 'about' | 'privacy' }) {
  const { t } = useLocale();
  return <article className="page narrow prose"><Link className="back-link" to="/">← {t('Check an area', 'क्षेत्र की जाँच')}</Link><p className="eyebrow">KilnWatch</p>{kind === 'about' ? <>
    <h1>{t('Evidence first.\nInspection next.', 'पहले साक्ष्य।\nफिर निरीक्षण।')}</h1><p className="lead">{t('KilnWatch helps residents turn questions about nearby brick kilns into a careful request for inspection.', 'KilnWatch निवासियों को आसपास के ईंट भट्ठों के बारे में सवालों को सावधान निरीक्षण अनुरोध में बदलने में मदद करता है।')}</p>
    <h2>{t('From imagery to a human finding', 'चित्र से मानव निरीक्षण तक')}</h2><ol className="process-list"><li><strong>{t('Observe', 'अवलोकन')}</strong><p>{t('A model looks for kiln-like shapes in satellite imagery. A prediction can be wrong, particularly about kiln type.', 'मॉडल उपग्रह चित्रों में भट्ठे जैसे आकार खोजता है। अनुमान गलत हो सकता है, विशेषकर भट्ठे के प्रकार का।')}</p></li><li><strong>{t('Publish approved evidence', 'स्वीकृत साक्ष्य प्रकाशित करना')}</strong><p>{t('Only records and imagery approved for public access belong in a resident portal. A satellite flag does not itself grant publication approval.', 'निवासी पोर्टल में केवल सार्वजनिक उपयोग के लिए स्वीकृत रिकॉर्ड और चित्र होने चाहिए। उपग्रह का संकेत अपने आप प्रकाशन की अनुमति नहीं देता।')}</p></li><li><strong>{t('Check on site', 'स्थल पर जाँच')}</strong><p>{t('An authorised inspector establishes site conditions and records a finding. Residents can request that inspection; this website cannot issue a verdict.', 'अधिकृत निरीक्षक स्थल की स्थिति जाँचकर निष्कर्ष दर्ज करता है। निवासी निरीक्षण का अनुरोध कर सकते हैं; यह वेबसाइट निर्णय नहीं दे सकती।')}</p></li></ol>
    <h2>{t('What you are exploring', 'आप क्या देख रहे हैं')}</h2><p>{config.mode === 'fixture' ? t('This local demonstration contains seven fictional records near a sample point at Pilkhuwa. Every location, human-reviewed example, measurement, population figure, and scene is sample data. The illustrative diagram is not a basemap. Coverage is bounded and explicitly reported for each search.', 'इस स्थानीय प्रदर्शन में पिलखुवा के नमूना बिंदु के पास सात काल्पनिक रिकॉर्ड हैं। हर स्थान, मानव-समीक्षित उदाहरण, माप, जनसंख्या और दृश्य नमूना डेटा है। सांकेतिक चित्र वास्तविक नक्शा नहीं है। कवरेज सीमित है और हर खोज में बताया जाता है।') : t('The public-service mode requires an approved server. Missing data remains unavailable; it is never replaced with sample results.', 'सार्वजनिक सेवा मोड के लिए स्वीकृत सर्वर आवश्यक है। अनुपलब्ध डेटा को नमूना परिणामों से नहीं बदला जाता।')}</p><p>{t('Neither an empty search nor a population estimate establishes air quality, measured emissions, health harm, or compliance. Observation dates are not construction dates.', 'खाली खोज या जनसंख्या अनुमान से हवा की गुणवत्ता, उत्सर्जन, स्वास्थ्य हानि या अनुपालन स्थापित नहीं होता। अवलोकन की तिथि निर्माण की तिथि नहीं है।')}</p>
    <h2>{t('Sources and attribution', 'स्रोत और श्रेय')}</h2><p>{config.mode === 'fixture' ? t('Illustrative diagram and synthetic 256-pixel vector scenes: KilnWatch, created for this demonstration. No real satellite imagery, private inspection photographs, training imagery, or third-party map tiles are used.', 'सांकेतिक चित्र और 256-पिक्सेल काल्पनिक दृश्य: KilnWatch, इस प्रदर्शन के लिए बनाए गए। वास्तविक उपग्रह चित्र, निजी निरीक्षण तस्वीरें, प्रशिक्षण चित्र या बाहरी मानचित्र टाइलें उपयोग नहीं की गई हैं।') : t('Geographic diagram: KilnWatch, without third-party map tiles. Published evidence identifies its source, acquisition date, and resolution on each record where supplied.', 'भौगोलिक चित्र: KilnWatch, बिना बाहरी मानचित्र टाइलों के। प्रत्येक रिकॉर्ड पर उपलब्ध प्रकाशित साक्ष्य का स्रोत, अवलोकन तिथि और रिज़ॉल्यूशन दिया जाता है।')}</p><p><a href="https://mpcb.gov.in/sites/default/files/standing_orders/Environmental%20Standards%20for%20Brick%20Kilns%20vide%20notification.pdf" target="_blank" rel="noreferrer">MoEF&CC · G.S.R. 143(E) · 22 February 2022 (PDF)</a></p><p>{t('Official notification hosted by the Maharashtra Pollution Control Board. Rule pages explain which reference is used and what remains unassessed. UP habitation applicability is unresolved; the central reference is not applied as a local verdict.', 'महाराष्ट्र प्रदूषण नियंत्रण बोर्ड द्वारा प्रकाशित आधिकारिक अधिसूचना। नियम पृष्ठ संदर्भ और बाकी आकलन समझाते हैं। उत्तर प्रदेश में आवास दूरी का लागू मानदंड अनिश्चित है; केंद्रीय संदर्भ को स्थानीय निर्णय नहीं माना गया है।')}</p>
  </> : <>
    <h1>{t('Your area. Your draft.\nYour choice.', 'आपका क्षेत्र। आपका मसौदा।\nआपकी पसंद।')}</h1><p className="lead">{t('This local portal starts without accounts, analytics, or cloud draft storage.', 'यह स्थानीय पोर्टल बिना खाते, एनालिटिक्स या क्लाउड मसौदा संग्रह के चलता है।')}</p>
    <h2>{t('Location and searches', 'स्थान और खोज')}</h2><p>{t('Location is requested only when you press “Use my location.” It requests one position, not continuous tracking. Your browser or operating system may use its location services. Manual coordinates and sample places work without permission.', 'स्थान केवल “मेरा स्थान उपयोग करें” दबाने पर माँगा जाता है। एक बार स्थान लिया जाता है, लगातार निगरानी नहीं की जाती। ब्राउज़र या ऑपरेटिंग सिस्टम अपनी स्थान सेवा उपयोग कर सकता है। निर्देशांक और नमूना स्थान बिना अनुमति के काम करते हैं।')}</p><p>{t('In sample mode, typed places and coordinates are processed locally. There is no external geocoder or map provider. Public-service mode, when configured, sends the search centre and radius to the configured public API. It does not send a department token.', 'नमूना मोड में स्थान और निर्देशांक स्थानीय रूप से संसाधित होते हैं। बाहरी जियोकोडर या मानचित्र सेवा नहीं है। कॉन्फ़िगर किए गए सार्वजनिक सेवा मोड में खोज केंद्र और दायरा सार्वजनिक API को जाते हैं। विभाग का टोकन नहीं भेजा जाता।')}</p>
    <h2>{t('Drafts and personal details', 'मसौदे और व्यक्तिगत जानकारी')}</h2><p>{t('Selected records, personal details, observations, and edited drafts stay in this tab’s memory. They are lost on refresh or closing the tab. Nothing is submitted, emailed, or uploaded. Copy, Download, and Print are explicit actions; their outputs may contain the personal details you entered. Your exact location is excluded unless you choose to include it.', 'चुने रिकॉर्ड, व्यक्तिगत जानकारी, अवलोकन और संपादित मसौदे इसी टैब की मेमोरी में रहते हैं। रीफ़्रेश या बंद करने पर खो जाते हैं। कुछ जमा, ईमेल या अपलोड नहीं किया जाता। कॉपी, डाउनलोड और प्रिंट आपके स्पष्ट कार्य हैं; इनमें आपके द्वारा दर्ज व्यक्तिगत जानकारी हो सकती है। सटीक स्थान आपकी पसंद के बिना शामिल नहीं होता।')}</p>
    <h2>{t('What is stored', 'क्या सहेजा जाता है')}</h2><p>{t('Only language and appearance preferences use local storage. There is no location or draft storage, behavioral analytics, conversation logging, or service worker. Your browser may keep downloaded files, copied text, print output, or ordinary static asset caches under its own settings.', 'केवल भाषा और रंग रूप की पसंद लोकल स्टोरेज में रहती है। स्थान या मसौदा संग्रह, व्यवहार एनालिटिक्स, बातचीत लॉग या सर्विस वर्कर नहीं है। ब्राउज़र अपनी सेटिंग के अनुसार डाउनलोड, कॉपी किए पाठ, प्रिंट या साधारण स्थिर फ़ाइल कैश रख सकता है।')}</p>
    <h2>{t('External sources', 'बाहरी स्रोत')}</h2><p>{t('Official source links open only when you choose them, with no referrer. Those sites apply their own policies. In public mode, evidence is fetched only from explicitly configured HTTPS hosts. No arbitrary image proxy is provided.', 'आधिकारिक स्रोत लिंक केवल आपके चुनने पर, बिना रेफ़रर के खुलते हैं। उन साइटों की अपनी नीतियाँ हैं। सार्वजनिक मोड में चित्र केवल कॉन्फ़िगर किए गए HTTPS होस्ट से आएँगे। मनमाना चित्र प्रॉक्सी नहीं है।')}</p>
  </>}</article>;
}
