import { Link, useNavigate, useParams } from 'react-router-dom';
import { useState } from 'react';
import { client, config } from '../../data/client';
import { assessed, safeSource } from '../../data/model';
import { useApp } from '../../app/state';
import { useLocale } from '../../i18n';
import { Arrow, ErrorState, Loading, Status, useResource } from '../../components/shared';
import { Evidence } from '../evidence/Evidence';
import { describe, missingFacts } from '../complaint/draft';

export function KilnPage() {
  const { id = '' } = useParams(); const { t, local, number, date, language } = useLocale();
  const resource = useResource(signal => client.detail(id, signal), id); const s = useApp(); const navigate = useNavigate();
  const [explanation, setExplanation] = useState<'explain' | 'missing' | null>(null);
  if (resource.error) return <div className="page narrow"><ErrorState error={resource.error} retry={resource.retry} /></div>;
  if (!resource.value) return <div className="page"><Loading /></div>;
  const k = resource.value, selected = s.basket.some(item => item.id === k.id), sample = config.mode === 'fixture';
  return <div className="page detail-page"><Link className="back-link" to="/area">← {t('Back to area', 'क्षेत्र पर वापस जाएँ')}</Link>
    <div className="record-heading"><div><p className="eyebrow">{t('A record to understand', 'समझने के लिए एक रिकॉर्ड')}</p><h1>{local(k.name)}</h1><p className="mono record-code">{k.id}</p><Status kiln={k} /></div><div className="observation"><p className="eyebrow">{t('Latest observation', 'नवीनतम अवलोकन')}</p><strong>{date(k.last_seen)}</strong><p className="help">{sample ? t('Sample date · fictional site', 'नमूना तिथि · काल्पनिक स्थल') : t('Observation, not construction date', 'अवलोकन, निर्माण की तिथि नहीं')}</p></div></div>
    {k.human_reviewed && sample && <p className="notice">{t('Fictitious human-reviewed example. No real inspection is represented.', 'मानव-समीक्षित स्थिति का काल्पनिक उदाहरण। यह वास्तविक निरीक्षण नहीं है।')}</p>}
    <div className="detail-grid"><div><Evidence key={id} kiln={k} /><section className="record-section"><div className="section-heading"><h2>{t('What the rules tell us', 'नियम क्या बताते हैं')}</h2><span className="small muted">{t('Measurements, with context', 'संदर्भ सहित माप')}</span></div>{k.assessments.map(a => <article className="rule-card" key={a.rule_id}><Link className="citation mono" to={`/rules/${a.rule_id}`}>{a.rule_id} <Arrow /></Link>{assessed(a) ? <><div className="rule-measure"><strong className="mono">{number(a.measured_distance_m!)} {t('m', 'मी')}</strong><span>{sample ? t('sample distance · reference threshold', 'नमूना दूरी · संदर्भ सीमा') : t('measured distance · supplied threshold', 'मापी गई दूरी · दी गई सीमा')} <b className="mono">{number(a.threshold_m!)} {t('m', 'मी')}</b></span></div><div className="distance-bar" aria-hidden="true"><span style={{ width: `${Math.min(100, a.measured_distance_m! / a.threshold_m! * 100)}%` }} /><i /></div><p className="help">{sample ? t('Sample assessment only. Applicability and measurement require site verification.', 'केवल नमूना आकलन। लागू नियम और माप की स्थल पर पुष्टि आवश्यक है।') : t('Published assessment. Confirm site conditions with an authorised inspector.', 'प्रकाशित आकलन। अधिकृत निरीक्षक से स्थल की स्थिति की पुष्टि कराएँ।')}</p><a href={safeSource(a.source_url)} rel="noreferrer" target="_blank">{t('Read the cited source', 'दिए गए स्रोत को पढ़ें')} <Arrow /></a></> : <><h3>{t('Not assessed', 'आकलन नहीं हुआ')}</h3><p>{t('The applicable rule or measurement has not been established. This is not a compliance finding.', 'लागू नियम या माप स्थापित नहीं किया गया है। यह अनुपालन का निष्कर्ष नहीं है।')}</p></>}</article>)}</section></div>
      <aside className="detail-aside"><section className="card"><p className="eyebrow">{t('Model prediction', 'मॉडल का अनुमान')}</p><h2>{['FCBK', 'CFCBK', 'Zigzag'].includes(k.prediction.type) ? k.prediction.type : t('Type unknown', 'प्रकार अज्ञात')}</h2><p>{t('Confirm on site', 'स्थल पर पुष्टि करें')}</p><p className="help">{t('A model score does not verify technology, fuel, or operation.', 'मॉडल का स्कोर तकनीक, ईंधन या संचालन की पुष्टि नहीं करता।')}</p><dl><div><dt>{t('Model score', 'मॉडल स्कोर')}</dt><dd className="mono">{k.prediction.score === null ? '—' : number(k.prediction.score, 2)}</dd></div><div><dt>{t('Latitude', 'अक्षांश')}</dt><dd className="mono">{k.centroid[1].toFixed(5)}</dd></div><div><dt>{t('Longitude', 'देशांतर')}</dt><dd className="mono">{k.centroid[0].toFixed(5)}</dd></div></dl></section>
      <section className="card"><p className="eyebrow">{t('Population context', 'जनसंख्या का संदर्भ')}</p>{k.exposure ? <><h2>{number(k.exposure.people)} <small>{t('people', 'लोग')}</small></h2><p>{t('within', 'दायरे में')} {number(k.exposure.radius_m)} {t('m', 'मी')}</p><p className="help">{local(k.exposure.source)} · {date(k.exposure.estimated_at)}</p></> : <><h2 className="small-heading">{t('Exposure estimate not available', 'जनसंख्या प्रभाव का अनुमान उपलब्ध नहीं')}</h2><p className="help">{t('Missing data does not mean zero people are nearby.', 'जानकारी न होने का अर्थ यह नहीं कि आसपास कोई नहीं रहता।')}</p></>}</section>
      <section className="card explanation"><p className="eyebrow">{t('Make sense of this record', 'इस रिकॉर्ड को समझें')}</p><h2>{t('What can I ask?', 'मैं क्या पूछ सकता हूँ?')}</h2><p className="help">{t('Template-based explanations from this record. No live assistant.', 'इस रिकॉर्ड पर आधारित तय प्रारूप के स्पष्टीकरण। लाइव सहायक नहीं।')}</p><div className="explain-actions"><button className="secondary" onClick={() => setExplanation('explain')}>{t('Explain this record', 'इस रिकॉर्ड को समझाएँ')} <span aria-hidden="true">→</span></button><button className="secondary" onClick={() => setExplanation('missing')}>{t('What is missing?', 'क्या जानकारी बाकी है?')} <span aria-hidden="true">→</span></button></div>{explanation && <div className="explanation-answer" role="status"><span className="sample-tag">{sample ? t('Sample explanation', 'नमूना स्पष्टीकरण') : t('Record explanation', 'रिकॉर्ड का स्पष्टीकरण')}</span>{explanation === 'explain' ? <p>{describe(k, language, sample)}</p> : <ul>{missingFacts(k, language).map(f => <li key={f}>{f}</li>)}</ul>}<Link className="citation mono" to={`/kilns/${k.id}`}>{k.id}</Link></div>}</section>
      <section className="draft-callout"><h2>{t('Turn questions into a request.', 'सवालों को अनुरोध में बदलें।')}</h2><p>{t('Add this record to an editable draft asking for an inspection.', 'इस रिकॉर्ड को निरीक्षण का अनुरोध करने वाले संपादन योग्य मसौदे में जोड़ें।')}</p><button className={selected ? 'secondary full' : 'primary full'} disabled={!selected && s.basket.length >= 10} onClick={() => s.changeBasket(k)}>{selected ? t('Remove from draft', 'मसौदे से हटाएँ') : t('Add to inspection draft', 'निरीक्षण मसौदे में जोड़ें')}</button>{!selected && s.basket.length >= 10 && <p>{t('A draft can include up to 10 records.', 'मसौदे में अधिकतम 10 रिकॉर्ड हो सकते हैं।')}</p>}<button className="text-button" onClick={() => { if (selected || s.changeBasket(k)) navigate('/complaint'); }}>{t('Prepare an inspection request', 'निरीक्षण का अनुरोध तैयार करें')} <Arrow /></button></section></aside>
    </div>
  </div>;
}

export function RulePage() {
  const { id = '' } = useParams(); const { t, local } = useLocale();
  const r = useResource(signal => client.rule(id, signal), id);
  if (r.error) return <div className="page narrow"><ErrorState error={r.error} retry={r.retry} /></div>;
  if (!r.value) return <div className="page"><Loading /></div>;
  const rule = r.value;
  return <article className="page narrow prose"><Link className="back-link" to="/area">← {t('Check an area', 'क्षेत्र की जाँच')}</Link><p className="eyebrow">{t('Rule reference', 'नियम का संदर्भ')}</p><p className="citation mono">{rule.id}</p><h1>{local(rule.name)}</h1><p className="lead">{local(rule.explanation)}</p><dl><div><dt>{t('Jurisdiction', 'अधिकार क्षेत्र')}</dt><dd>{local(rule.jurisdiction)}</dd></div><div><dt>{t('Reference date', 'संदर्भ तिथि')}</dt><dd>{rule.effective_date ?? t('Not supplied', 'नहीं दिया गया')}</dd></div><div><dt>{t('Threshold for this portal', 'इस पोर्टल के लिए सीमा')}</dt><dd>{rule.threshold_m === null ? t('Not established', 'स्थापित नहीं') : `${rule.threshold_m} m · ${config.mode === 'fixture' ? t('sample reference only', 'केवल नमूना संदर्भ') : t('reference only', 'केवल संदर्भ')}`}</dd></div></dl><section className="notice"><h2>{t('Before drawing a conclusion', 'निष्कर्ष से पहले')}</h2><p>{local(rule.limitation)}</p></section><h2>{t('Source', 'स्रोत')}</h2><p>{rule.source_title}</p>{safeSource(rule.source_url) ? <a href={safeSource(rule.source_url)} target="_blank" rel="noreferrer">{t('Open official notification (PDF)', 'आधिकारिक अधिसूचना खोलें (PDF)')} <Arrow /></a> : <p>{t('An approved source link is not available.', 'स्वीकृत स्रोत लिंक उपलब्ध नहीं है।')}</p>}<p className="help">{t('An authority must establish the current rules applicable to a site. A rule reference is not an inspection finding.', 'स्थल पर लागू वर्तमान नियम संबंधित प्राधिकरण को स्थापित करने हैं। नियम का संदर्भ निरीक्षण का निष्कर्ष नहीं है।')}</p></article>;
}
